- Tratamento de NA's e Adequações
```{r}
#Importando base de dados
dados <- read.csv("Tempo.csv", sep= ";", na.strings= "", stringsAsFactors= T)
head(dados)
#Verificação de dados
summary(dados)
```
- Visualização gráfica dos dados, para ajudar na limpeza e tratamento
```{r}
#Aparência
counts <- table(dados$Aparencia)
counts
barplot(counts, main="Aparencia", xlab="Aparencia")
```

```{r}
#Vento
counts <- table(dados$Vento)
counts
barplot(counts, main="Vento", xlab="Vento")

```

```{r}
#Jogar
counts <- table(dados$Jogar)
counts
barplot(counts, main="Jogar", xlab="Jogar")
```
- Explorando colunas
```{r}
#Temperatura
summary(dados$Temperatura)
boxplot(dados$Temperatura)
hist(dados$Temperatura)
```

```{r}
#Umidade
summary(dados$Umidade)
boxplot(dados$Umidade)
hist(dados$Umidade)
```
- Tratando NA's
```{r}
#Visualização de NA's
dados[!complete.cases(dados),]
```
- Tratamento da coluna Aparência
```{r}
#Visualização
summary(dados$Aparencia)
#Não possui NA's
dados[is.na(dados$Aparencia),]
#Preencher valores incoerentes com a mediana 
#Substituição com a moda(Valor que mais se destaca)
dados[dados$Aparencia == "menos",]$Aparencia = "sol"
#visualização
summary(dados$Aparencia)
#Removendo excessos desnecessários
dados$Aparencia = factor(dados$Aparencia)
summary(dados$Aparencia)
```
- Tratando coluna Temperatura
```{r}
#Visualização
summary(dados$Temperatura)
#Checagem de excendente
dados[dados$Temperatura < -130 | dados$Temperatura > 130,]$Temperatura
#Não possui NA's
dados[is.na(dados$Temperatura)]
#Calculando Mediana
median(dados$Temperatura)
#Substituição de valores incorretos
dados[dados$Temperatura < -130 | dados$Temperatura > 130,]$Temperatura = median(dados$Temperatura)
#visualização
dados[dados$Temperatura < -130 | dados$Temperatura > 130,]$Temperatura
summary(dados$Temperatura)
```
- Tratando coluna Umidade, domínio e NA'S
```{r}
#Visualização
summary(dados$Umidade)
#Checagem de excendente
dados[dados$Umidade < 0 | dados$Umidade > 100 ,]$Umidade
#checagem de NA's
dados[is.na(dados$Umidade),]
#Atribuir NA's a mediana
dados[is.na(dados$Umidade),]$Umidade = median(dados$Umidade,na.rm = T)
#Substituição
dados[dados$Umidade < 0 | dados$Umidade > 100,]$Umidade = median(dados$Umidade)
#Verificação
dados[dados$Umidade < 0 | dados$Umidade > 100,]$Umidade
summary(dados$Umidade)
```
- Tratando coluna Vento e suas NA's
```{r}
#Visualização
summary(dados$Vento)
#tratando NA's
dados[is.na(dados$Vento),]
#Substituição
dados[is.na(dados$Vento),]$Vento = 'FALSO'
#Verificação
dados[is.na(dados$Vento),]
summary(dados$Vento)
```


